openapi: 3.0.0
info:
  title: My API
  description: API for user authentication and subscriptions
  version: 1.0.0
servers:
  - url: https://your-api-gateway-url  # Replace with your actual API Gateway URL
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
              required:
                - email
                - username
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                remember_me:
                  type: boolean
              required:
                - email
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /updatePassword:
    post:
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                new_password:
                  type: string
              required:
                - current_password
                - new_password
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Invalid current password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /resetPassword:
    post:
      summary: Send a password reset email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: Password reset email sent successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /buySubscription:
    post:
      summary: Buy a subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_method_id:
                  type: string
                price_id:
                  type: string
              required:
                - payment_method_id
                - price_id
      responses:
        '200':
          description: Subscription created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription_id:
                    type: string
                  client_secret:
                    type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /cancelSubscription:
    post:
      summary: Cancel a subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subscription_id:
                  type: string
              required:
                - subscription_id
      responses:
        '200':
          description: Subscription canceled successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /getBillingHistory:
    get:
      summary: Get billing history
      responses:
        '200':
          description: Billing history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    amount:
                      type: integer
                    currency:
                      type: string
                    status:
                      type: string
                    description:
                      type: string
                    date:
                      type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /socialLogin:
    post:
      summary: Social login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provider:
                  type: string
                id_token:
                  type: string
                access_token:
                  type: string
              required:
                - provider
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
